### ISSUE TITLE
Getting nav messages but no meta data displaying on app

### ISSUE THREAD

**Issue by noelpedro** [acebrianjuan/gnss-sdr-monitor#13]
Hi Ace,

I’m doing real time processing with gnsssdr v13.

Having the issue where I have 4 channels producing nav messages. Although I’m successfully connecting client and server I see nothing being displayed on host machine running your app on Ubuntu 18.

Furthermore, I don’t get any PVT on my embedded device.

I was wondering if you’ve tested your app with gnsssdr v13?

it appears as if there is a disconnect between gnsssdr synchros.

maybe it’s a bug with gnsssdr and not your app. But was hoping you have experienced something similar.

**Comment by acebrianjuan** [comment]
Hi @noelpedro,

> I was wondering if you’ve tested your app with gnsssdr v13?

I have just tested the GUI with the latest version of gnss-sdr available on the `next` branch (`v0.0.14.git-next-786feddd1`) and everything is working fine as you can see in the screenshot, so I assume it should also work with v13.

![gnss-sdr-monitor_screenshot](https://user-images.githubusercontent.com/34104100/119805316-6ec11a00-bee1-11eb-9d57-c277b4e6e9e2.png)

> Having the issue where I have 4 channels producing nav messages. Although I’m successfully connecting client and server I see nothing being displayed on host machine running your app on Ubuntu 18.

If these 4 channels are delivering observables then they should appear in the channels table view of the GUI (marked with the red arrow).

Please check that you have enabled the serialization streams in your GNSS-SDR configuration file and that your UDP port numbers match with those in the GUI preferences. The instructions in the [README](https://github.com/acebrianjuan/gnss-sdr-monitor/blob/master/README.md) file are aimed to guide you through this process.

Do let me know if you have any questions.
I hope this helps.

Regards,
Álvaro

**Comment by noelpedro** [comment]
I'm producing empty observables for some reason.

**Comment by noelpedro** [comment]
Should the TOW[ms] values be the same or fairly close for all CHannels being tracked? I'm trying to fix why I'm not able the get position fix when I'm getting 4 valid observables. All 4 channesl that I'm tracking in real time have different TOW[ms] on gnss-sdr monitor. And also getting RTKLIB Error when attempting to calculate position.

**Comment by noelpedro** [comment]
I see in the image abobve 4 satellites have same TOW

**Comment by noelpedro** [comment]
I'm also getting positive and negative pseudoranges, I see all positive above for u.

**Comment by acebrianjuan** [comment]
Hi @noelpedro,

The gnss-sdr-monitor GUI merely acts as a _"viewer"_ of the GNSS-SDR internals and it only displays the values as they arrive in the protobuf data stream. So if you see any unusual values in the GUI you should check what's going on upstream in your gnss-sdr instance.

By the way, in my experience, I have never seen negative pseudoranges while working with gnss-sdr. They have always been positive as far as I know.

I hope this helps.

Regards,
Álvaro

**Comment by noelpedro** [comment]
Thanks. I was able to get a fix now.

but still seeing those negative pseudoranges.

True, distance should be greater than or equal to zero.
