### ISSUE TITLE
Don't have detail information in interface

### ISSUE THREAD

**Issue by yangfan852219770** [acebrianjuan/gnss-sdr-monitor#14]
Hi,
I can get PVT messages, but there is nothing detail information in interface. Like this:
![QQ图片20210705105833](https://user-images.githubusercontent.com/32131462/124424306-66d67e80-dd99-11eb-89a8-498009424603.png)
Maybe I don't know why.

**Comment by acebrianjuan** [comment]
Hi @yangfan852219770,

Please check that you have enabled the Monitor block in your GNSS-SDR configuration file and make sure that the UDP port number (`Monitor.udp_port`) matches with the `GNSS_Synchro port` in the preferences panel of the GUI (`Edit > Preferences`).

The instructions in the [README](https://github.com/acebrianjuan/gnss-sdr-monitor/blob/master/README.md) file will help you.

Cheers,
Álvaro

**Comment by yangfan852219770** [comment]
Thanks @acebrianjuan 
In my configuration file and **Preferences** , there are some errors.  I have sovled this problem referring to your **README** file.

**Comment by acebrianjuan** [comment]
Awesome! I am closing this issue then.
