### ISSUE TITLE
Ubuntu version

### ISSUE THREAD

**Issue by carlesfernandez** [acebrianjuan/gnss-sdr-monitor#4]
Please state in the README file which Ubuntu version the package list is referred to.

For instance, the provided list does not work for Ubuntu 16.04.

**Comment by acebrianjuan** [comment]
Dear @carlesfernandez,

I have added the Ubuntu versions upon which the gnss-sdr-monitor GUI can be built using the packages listed in the [README](https://github.com/acebrianjuan/gnss-sdr-monitor/blob/master/README.md) file. You can review the fix in commit d538c86.

Please note that, as of today, the GUI is being developed using Qt version 5.9.0, so this means that compatibility is guaranteed only for Ubuntu 18.04 or above (whose official packages use Qt versions 5.9.5 and above). To my knowledge, the official Qt packages in Ubuntu 16.04 are frozen at version 5.5.1, so this this means that building the GUI will not be possible unless you upgrade your Qt installation manually.

Regards,
Álvaro

**Comment by carlesfernandez** [comment]
Thanks!
