### ISSUE TITLE
Multi-threaded?

### ISSUE THREAD

**Issue by noelpedro** [acebrianjuan/gnss-sdr-monitor#7]
Hi I'm assuming that each channel is on its own thread similar to gnss-sdr?

I'm trying to share data between channels, should I edit gnss-sdr source code or can I accomplish this simply on the gnss-sdr monitor side of things??

thanks

**Comment by acebrianjuan** [comment]
Hi @noelpedro,

> Hi I'm assuming that each channel is on its own thread similar to gnss-sdr?

No, the gnss-sdr-monitor GUI is a single-threaded application.

> I'm trying to share data between channels, should I edit gnss-sdr source code or can I accomplish this simply on the gnss-sdr monitor side of things??

I don't know what you mean by _"share data between channels"_ nor what you are trying to accomplish but, on the gnss-sdr-monitor side, if you want to know where the data for each channel is stored, check the map containers in the [ChannelTableModel](https://github.com/acebrianjuan/gnss-sdr-monitor/blob/master/src/channel_table_model.h) class:

https://github.com/acebrianjuan/gnss-sdr-monitor/blob/eb1820a78ca33e6613095166bab16000de5a6a83/src/channel_table_model.h#L72-L79

I hope this information is useful to you.

Regards,
Álvaro

**Comment by acebrianjuan** [comment]
Hi @noelpedro,

> Hi I'm assuming that each channel is on its own thread similar to gnss-sdr?

No, the gnss-sdr-monitor GUI is a single-threaded application.

> I'm trying to share data between channels, should I edit gnss-sdr source code or can I accomplish this simply on the gnss-sdr monitor side of things??

I don't know what you mean by _"share data between channels"_ nor what you are trying to accomplish but, on the gnss-sdr-monitor side, if you want to know where the data for each channel is stored, check the map containers in the [ChannelTableModel](https://github.com/acebrianjuan/gnss-sdr-monitor/blob/master/src/channel_table_model.h) class:

https://github.com/acebrianjuan/gnss-sdr-monitor/blob/eb1820a78ca33e6613095166bab16000de5a6a83/src/channel_table_model.h#L72-L79

I hope this information is useful to you.

Regards,
Álvaro
